// Auto-generated by generate_roms.py
window.ROMS_LIST = [
    {
        "id": "darkrising-kaizo-fixed (1).zip",
        "title": "Darkrising Kaizo Fixed (1)",
        "filename": "darkrising-kaizo-fixed (1).zip",
        "description": "Detected from roms folder"
    },
    {
        "id": "HnS v1.2.1.zip",
        "title": "Hns V1.2.1",
        "filename": "HnS v1.2.1.zip",
        "description": "Detected from roms folder"
    },
    {
        "id": "PK Alternate Evolutions.zip",
        "title": "Pk Alternate Evolutions",
        "filename": "PK Alternate Evolutions.zip",
        "description": "Detected from roms folder"
    },
    {
        "id": "Roaring Red V1.6.zip",
        "title": "Roaring Red V1.6",
        "filename": "Roaring Red V1.6.zip",
        "description": "Detected from roms folder"
    },
    {
        "id": "spades&clubs demo 0.2.1.zip",
        "title": "Spades&Clubs Demo 0.2.1",
        "filename": "spades&clubs demo 0.2.1.zip",
        "description": "Detected from roms folder"
    },
    {
        "id": "TradenStache.zip",
        "title": "Tradenstache",
        "filename": "TradenStache.zip",
        "description": "Detected from roms folder"
    }
];
