// Auto-generated by generate_roms.py
window.ROMS_LIST = [
    {
        "id": "awful demo 2.0.5.zip",
        "title": "Awful Demo 2.0.5",
        "filename": "awful demo 2.0.5.zip",
        "description": "Detected from roms folder"
    },
    {
        "id": "bills secret garden v1.1.zip",
        "title": "Bills Secret Garden V1.1",
        "filename": "bills secret garden v1.1.zip",
        "description": "Detected from roms folder"
    },
    {
        "id": "ceruleanaquarium.zip",
        "title": "Ceruleanaquarium",
        "filename": "ceruleanaquarium.zip",
        "description": "Detected from roms folder"
    },
    {
        "id": "coastal v1.6.zip",
        "title": "Coastal V1.6",
        "filename": "coastal v1.6.zip",
        "description": "Detected from roms folder"
    },
    {
        "id": "darkrising-kaizo-fixed (1).zip",
        "title": "Darkrising Kaizo Fixed (1)",
        "filename": "darkrising-kaizo-fixed (1).zip",
        "description": "Detected from roms folder"
    },
    {
        "id": "ElafGold.zip",
        "title": "Elafgold",
        "filename": "ElafGold.zip",
        "description": "Detected from roms folder"
    },
    {
        "id": "evolved.zip",
        "title": "Evolved",
        "filename": "evolved.zip",
        "description": "Detected from roms folder"
    },
    {
        "id": "financial stability (completed).zip",
        "title": "Financial Stability (Completed)",
        "filename": "financial stability (completed).zip",
        "description": "Detected from roms folder"
    },
    {
        "id": "HnS v1.2.1.zip",
        "title": "Hns V1.2.1",
        "filename": "HnS v1.2.1.zip",
        "description": "Detected from roms folder"
    },
    {
        "id": "lazygreen v1.1.15.zip",
        "title": "Lazygreen V1.1.15",
        "filename": "lazygreen v1.1.15.zip",
        "description": "Detected from roms folder"
    },
    {
        "id": "lil' emrld v1.2.zip",
        "title": "Lil' Emrld V1.2",
        "filename": "lil' emrld v1.2.zip",
        "description": "Detected from roms folder"
    },
    {
        "id": "maxiesisland v1.4.zip",
        "title": "Maxiesisland V1.4",
        "filename": "maxiesisland v1.4.zip",
        "description": "Detected from roms folder"
    },
    {
        "id": "mega-emerald-x-y.zip",
        "title": "Mega Emerald X Y",
        "filename": "mega-emerald-x-y.zip",
        "description": "Detected from roms folder"
    },
    {
        "id": "mini v1.0.10.zip",
        "title": "Mini V1.0.10",
        "filename": "mini v1.0.10.zip",
        "description": "Detected from roms folder"
    },
    {
        "id": "Pengies Silly Emerald Hack.zip",
        "title": "Pengies Silly Emerald Hack",
        "filename": "Pengies Silly Emerald Hack.zip",
        "description": "Detected from roms folder"
    },
    {
        "id": "PK Alternate Evolutions.zip",
        "title": "Pk Alternate Evolutions",
        "filename": "PK Alternate Evolutions.zip",
        "description": "Detected from roms folder"
    },
    {
        "id": "PK CW v523d.zip",
        "title": "Pk Cw V523D",
        "filename": "PK CW v523d.zip",
        "description": "Detected from roms folder"
    },
    {
        "id": "PK FireGold Version h.1.8.zip",
        "title": "Pk Firegold Version H.1.8",
        "filename": "PK FireGold Version h.1.8.zip",
        "description": "Detected from roms folder"
    },
    {
        "id": "Pokemon - Doubles FireRed 1.0.gba",
        "title": "Pokemon   Doubles Firered 1.0",
        "filename": "Pokemon - Doubles FireRed 1.0.gba",
        "description": "Detected from roms folder"
    },
    {
        "id": "Pokemon_Abra_Adventure v1 (1).zip",
        "title": "Pokemon Abra Adventure V1 (1)",
        "filename": "Pokemon_Abra_Adventure v1 (1).zip",
        "description": "Detected from roms folder"
    },
    {
        "id": "pokemon_adventure_blue_chapter_b1.1.zip",
        "title": "Pokemon Adventure Blue Chapter B1.1",
        "filename": "pokemon_adventure_blue_chapter_b1.1.zip",
        "description": "Detected from roms folder"
    },
    {
        "id": "pokemon_apollo_beta_0.3.zip",
        "title": "Pokemon Apollo Beta 0.3",
        "filename": "pokemon_apollo_beta_0.3.zip",
        "description": "Detected from roms folder"
    },
    {
        "id": "Pokemon Emerald Semi Randomizer (a3).zip",
        "title": "Pokemon Emerald Semi Randomizer (A3)",
        "filename": "Pokemon Emerald Semi Randomizer (a3).zip",
        "description": "Detected from roms folder"
    },
    {
        "id": "pokemon_fat_kid_beta_1.2.4.gba.zip",
        "title": "Pokemon Fat Kid Beta 1.2.4.Gba",
        "filename": "pokemon_fat_kid_beta_1.2.4.gba.zip",
        "description": "Detected from roms folder"
    },
    {
        "id": "Pokemon Glazed (Unofficial v9.1.0).zip",
        "title": "Pokemon Glazed (Unofficial V9.1.0)",
        "filename": "Pokemon Glazed (Unofficial v9.1.0).zip",
        "description": "Detected from roms folder"
    },
    {
        "id": "Pokemon_Jungle_Completed.zip",
        "title": "Pokemon Jungle Completed",
        "filename": "Pokemon_Jungle_Completed.zip",
        "description": "Detected from roms folder"
    },
    {
        "id": "pokemon_liquid_crystal_beta_3.3.00100.gba.zip",
        "title": "Pokemon Liquid Crystal Beta 3.3.00100.Gba",
        "filename": "pokemon_liquid_crystal_beta_3.3.00100.gba.zip",
        "description": "Detected from roms folder"
    },
    {
        "id": "pokemon_lost_treasure.zip",
        "title": "Pokemon Lost Treasure",
        "filename": "pokemon_lost_treasure.zip",
        "description": "Detected from roms folder"
    },
    {
        "id": "Pokemon Lunar Alpha.zip",
        "title": "Pokemon Lunar Alpha",
        "filename": "Pokemon Lunar Alpha.zip",
        "description": "Detected from roms folder"
    },
    {
        "id": "pokemon_magikarps_adventure.zip",
        "title": "Pokemon Magikarps Adventure",
        "filename": "pokemon_magikarps_adventure.zip",
        "description": "Detected from roms folder"
    },
    {
        "id": "Pokemon Nidoqueen Version.zip",
        "title": "Pokemon Nidoqueen Version",
        "filename": "Pokemon Nidoqueen Version.zip",
        "description": "Detected from roms folder"
    },
    {
        "id": "Pokemon Run & Bun (v1.07).zip",
        "title": "Pokemon Run & Bun (V1.07)",
        "filename": "Pokemon Run & Bun (v1.07).zip",
        "description": "Detected from roms folder"
    },
    {
        "id": "pokemon_spice.zip",
        "title": "Pokemon Spice",
        "filename": "pokemon_spice.zip",
        "description": "Detected from roms folder"
    },
    {
        "id": "pokemon-team-rocket-blasting-off.zip",
        "title": "Pokemon Team Rocket Blasting Off",
        "filename": "pokemon-team-rocket-blasting-off.zip",
        "description": "Detected from roms folder"
    },
    {
        "id": "pokemon_thief_sapphire_completed.gba.zip",
        "title": "Pokemon Thief Sapphire Completed.Gba",
        "filename": "pokemon_thief_sapphire_completed.gba.zip",
        "description": "Detected from roms folder"
    },
    {
        "id": "Pokemon_Uranium_GBA_Version_Beta_1.zip",
        "title": "Pokemon Uranium Gba Version Beta 1",
        "filename": "Pokemon_Uranium_GBA_Version_Beta_1.zip",
        "description": "Detected from roms folder"
    },
    {
        "id": "pokemon_v_beta_1.zip",
        "title": "Pokemon V Beta 1",
        "filename": "pokemon_v_beta_1.zip",
        "description": "Detected from roms folder"
    },
    {
        "id": "Pokemon Wally Quest (v1.1).zip",
        "title": "Pokemon Wally Quest (V1.1)",
        "filename": "Pokemon Wally Quest (v1.1).zip",
        "description": "Detected from roms folder"
    },
    {
        "id": "Roaring Red V1.6.zip",
        "title": "Roaring Red V1.6",
        "filename": "Roaring Red V1.6.zip",
        "description": "Detected from roms folder"
    },
    {
        "id": "sinnoh-legacy-b2.0.zip",
        "title": "Sinnoh Legacy B2.0",
        "filename": "sinnoh-legacy-b2.0.zip",
        "description": "Detected from roms folder"
    },
    {
        "id": "spades&clubs demo 0.2.1.zip",
        "title": "Spades&Clubs Demo 0.2.1",
        "filename": "spades&clubs demo 0.2.1.zip",
        "description": "Detected from roms folder"
    },
    {
        "id": "spinspinspin v1.9.zip",
        "title": "Spinspinspin V1.9",
        "filename": "spinspinspin v1.9.zip",
        "description": "Detected from roms folder"
    },
    {
        "id": "TradenStache.zip",
        "title": "Tradenstache",
        "filename": "TradenStache.zip",
        "description": "Detected from roms folder"
    },
    {
        "id": "U_FR_Adventure_Red_Beta_15_Expansion_Fix_Patch_C.gba.zip",
        "title": "U Fr Adventure Red Beta 15 Expansion Fix Patch C.Gba",
        "filename": "U_FR_Adventure_Red_Beta_15_Expansion_Fix_Patch_C.gba.zip",
        "description": "Detected from roms folder"
    },
    {
        "id": "Wings of Chaos (Alpha 2).zip",
        "title": "Wings Of Chaos (Alpha 2)",
        "filename": "Wings of Chaos (Alpha 2).zip",
        "description": "Detected from roms folder"
    }
];
