import os
import json
import urllib.parse

# Configuration
ROMS_DIR = 'roms'
OUTPUT_FILE = 'games.js'
ALLOWED_EXTENSIONS = {'.gba', '.zip', '.gbc', '.gb'}

def generate_games_list():
    games = []
    
    # Check if directory exists
    if not os.path.exists(ROMS_DIR):
        print(f"Error: Directory '{ROMS_DIR}' not found.")
        return

    # Scan directory
    for filename in os.listdir(ROMS_DIR):
        ext = os.path.splitext(filename)[1].lower()
        if ext in ALLOWED_EXTENSIONS:
            # Create a user-friendly title
            title = os.path.splitext(filename)[0]
            title = title.replace('_', ' ').replace('-', ' ')
            title = title.title()
            
            game_entry = {
                "id": filename, 
                "title": title,
                "filename": filename,
                "description": "Detected from roms folder"
            }
            games.append(game_entry)
    
    # Sort games alphabetically
    games.sort(key=lambda x: x['title'])
    
    # Write to JS file
    try:
        with open(OUTPUT_FILE, 'w') as f:
            f.write("// Auto-generated by generate_roms.py\n")
            f.write("window.ROMS_LIST = ")
            json.dump(games, f, indent=4)
            f.write(";\n")
        print(f"Successfully generated {OUTPUT_FILE} with {len(games)} games.")
    except Exception as e:
        print(f"Error writing file: {e}")

if __name__ == "__main__":
    generate_games_list()
