// Game Configuration
// games.js provides window.ROMS_LIST

// Fallback list of games if games.js is missing or empty
const FALLBACK_GAMES = [
    { title: "HnS v1.2.1", filename: "HnS v1.2.1.zip", description: "Backup Import" },
    { title: "Roaring Red V1.6", filename: "Roaring Red V1.6.zip", description: "Backup Import" },
    { title: "TradenStache", filename: "TradenStache.zip", description: "Backup Import" },
    { title: "Spades & Clubs Demo 0.2.1", filename: "spades&clubs demo 0.2.1.zip", description: "Backup Import" }
];

// Emulator Configuration
const EJS_PATH_TO_DATA = "https://cdn.jsdelivr.net/gh/ethanaobrien/emulatorjs@main/data/";

function initGameList() {
    const grid = document.getElementById('games-grid');
    grid.innerHTML = ''; // Clear placeholder
    
    // Try to get games from global variable (generated by python script)
    // If not found, use the fallback list
    let games = window.ROMS_LIST;
    
    if (!games || games.length === 0) {
        console.warn('games.js not loaded or empty. Using fallback list.');
        games = FALLBACK_GAMES;
    }
    
    if (games.length === 0) {
        grid.innerHTML = '<p style="color:#aaa; grid-column: 1/-1;">No games found. Make sure <code>games.js</code> is generated by running <code>python3 generate_roms.py</code>.</p>';
        return;
    }
    
    games.forEach(game => {
        const card = document.createElement('div');
        card.className = 'game-card';
        card.onclick = () => loadGame(game);
        
        const title = document.createElement('div');
        title.className = 'game-title';
        title.textContent = game.title;
        
        const meta = document.createElement('div');
        meta.className = 'game-meta';
        meta.innerHTML = `<span class="game-icon">👾</span> ${game.description || 'GBA Rom'}`;
        
        card.appendChild(title);
        card.appendChild(meta);
        grid.appendChild(card);
    });
}

function loadGame(game) {
    const container = document.getElementById('game-container');
    
    // Clear previous game or placeholder
    container.innerHTML = '';
    
    // Create the game div required by EmulatorJS
    const gameDiv = document.createElement('div');
    gameDiv.style.width = '100%';
    gameDiv.style.height = '100%';
    gameDiv.style.maxWidth = '100%';
    gameDiv.id = 'game';
    container.appendChild(gameDiv);
    
    // Configure EmulatorJS
    window.EJS_player = '#game';
    window.EJS_core = 'gba';
    
    // Better fullscreen experience
    window.EJS_backgroundColor = '#000000'; 
    window.EJS_biosUrl = ''; 
    
    if (game.blobUrl) {
        window.EJS_gameUrl = game.blobUrl;
    } else {
        window.EJS_gameUrl = `roms/${encodeURIComponent(game.filename)}`; 
    }
    
    window.EJS_pathtodata = "https://cdn.jsdelivr.net/gh/ethanaobrien/emulatorjs@main/data/";
    window.EJS_startOnLoaded = true;
    
    // Speed / Fast Forward Setup
    // EmulatorJS automatically handles mobile touch controls.
    
    // Remove old script if exists
    const oldScript = document.getElementById('emulator-script');
    if (oldScript) oldScript.remove();
    
    // Inject the loader script
    const script = document.createElement('script');
    script.src = `${EJS_PATH_TO_DATA}loader.js`;
    script.id = 'emulator-script';
    script.async = true;
    
    script.onerror = function() {
        console.error("EmulatorJS script failed to load.");
        // Try fallback or just alert
        const container = document.getElementById('game-container');
        container.innerHTML = '<div class="placeholder-screen"><div class="placeholder-content"><h2>Error Loading Emulator</h2><p>Please check internet connection.</p></div></div>';
    };
    
    document.body.appendChild(script);
    
    // Scroll to game
    container.scrollIntoView({ behavior: 'smooth', block: 'center' });
    
    // Focus the game container so keyboard inputs go there immediately
    // Wait slightly for iframe to spawn
    setTimeout(() => {
        const gameContainer = document.getElementById('game-container');
        if(gameContainer) {
             gameContainer.tabIndex = 0; // Make focusable
             gameContainer.focus();
             // Focus the iframe if possible
             const iframe = gameContainer.querySelector('iframe');
             if(iframe) iframe.focus();
             
             // Additional click listener to steal focus back
             gameContainer.addEventListener('click', () => {
                 gameContainer.focus();
                 if(iframe) iframe.focus();
             });
        }
    }, 1000);
    
    // Show controls hint
    showControlsHint();
}

function showControlsHint() {
    const hint = document.getElementById('controls-hint');
    if(hint) {
        hint.style.display = 'block';
        hint.innerHTML = "<b>Controls:</b> Arrow Keys = Move, Z = A, X = B, Enter = Start, Shift = Select.<br><b>Fast Forward:</b> Hold SPACE Spacebar.<br><b>Mobile:</b> Play on Full Screen To be Better.";
    }
}

function setupFileUpload() {
    const fileInput = document.getElementById('file-upload');
    if (!fileInput) return;
    
    fileInput.addEventListener('change', function(e) {
        const file = e.target.files[0];
        if (!file) return;

        // Create a blob URL for the local file
        const blobUrl = URL.createObjectURL(file);
        
        const game = {
            title: file.name.replace(/\.(zip|gba|gbc|gb)$/i, ''),
            filename: file.name,
            description: "Custom Upload",
            blobUrl: blobUrl
        };
        
        loadGame(game);
    });
}


// Prevent scrolling globally for arrow keys and space (unless in input)
window.addEventListener("keydown", function(e) {
    if(e.target.tagName !== 'INPUT' && e.target.tagName !== 'TEXTAREA') {
        if([32, 37, 38, 39, 40].indexOf(e.keyCode) > -1) {
            e.preventDefault();
        }
    }
}, { capture: false, passive: false }); // Changed capture to false to match standard practice, maybe capture was too aggressive?

// Initialize on load
document.addEventListener('DOMContentLoaded', () => {
    initGameList();
    setupFileUpload();
});
